version: '3.8'

services:
  backend:
    build: ./cadastro-back
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/eteg
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - eteg-network

  frontend:
    build: ./cadastro-front
    container_name: frontend-app
    ports:
      - "3000:80"
    networks:
      - eteg-network

  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eteg
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eteg-network

volumes:
  postgres-data:


networks:
  eteg-network:
    driver: bridge
