version: '3.8'
services:
  backend:
    build: C:\Users\Carlos Eduardo\Projetos Pessoais\eteg-project\cadastro-back
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/eteg
    depends_on:
      - frontend

  frontend:
    build: C:\Users\Carlos Eduardo\Projetos Pessoais\eteg-project\cadastro-front
    container_name: frontend-app
    ports:
      - "3000:80"
